name: syncfusion_officecore
description: Syncfusion Flutter Office Core is a dependant library for Syncfusion Flutter XlsIO, written natively in Dart for creating Excel from scratch.
version: 21.1.35-beta
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_officecore

environment:
  sdk: ">=2.17.0 <3.0.0"  

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core: ^21.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter
