name: syncfusion_officechart
description: Syncfusion Flutter Office Chart is a library written natively in Dart for creating Office charts from scratch.
version: 20.2.36-beta.1
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_officechart

environment:
  sdk: ">=2.12.0 <3.0.0"  

dependencies:
  flutter:
    sdk: flutter
  xml: ">=5.1.0 <7.0.0"
  archive: ">=3.1.2 <4.0.0"
  syncfusion_flutter_xlsio: ^20.2.36

dev_dependencies:
  flutter_test:
    sdk: flutter
