name: syncfusion_flutter_maps
description: A Flutter Maps library for creating beautiful, interactive, and customizable maps from shape files or WMTS services to visualize the geographical area.
version: 20.2.36-beta
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_maps

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_core: ^20.2.36
      
  http: ">=0.12.0 <=0.13.4"
  vector_math: ">=2.1.0 <=3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  