name: syncfusion_flutter_datagrid_export
description: The Syncfusion Flutter DataGrid Export library is used to export the DataGrid content to Excel and Pdf format with several customization options.
version: 20.2.36-beta
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_datagrid_export

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  syncfusion_flutter_datagrid: ^20.2.36
  
  syncfusion_flutter_xlsio: ^20.2.36
  
  syncfusion_flutter_pdf: ^20.2.36

  collection: ">=1.9.0 <=2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
